Repository onuralpszr/CvCamera-Mobile, pull requests merged in 2022-10, with the labels that each got.

#3 opencv c++ path fix
  app/build.gradle
Labels: hacktoberfest-accepted

#7 fix: remove reflection for mListener, modify .gitignore, change setupOpenCV.sh permissions
  .gitignore
  app/src/main/java/com/os/cvCamera/ExtendJavaCamera2View.kt
  setupOpenCV.sh
Labels: enhancement

#14 feat: android-ci file added
  .github/workflows/android-ci.yml
Labels: dev-ci

#16 ci: update action/setup-java version to 3
  .github/workflows/android-ci.yml
Labels: dev-ci
